[package]
edition = "2021"
name = "bevystein"
version = "0.0.1"

[dependencies]
bevy = {package = "bevy", git = "https://github.com/bevyengine/bevy.git", rev = "026563c"}
bevy_mod_raycast = {path = "./crates/bevy_mod_raycast"}
big-brain = {path = "./crates/big-brain"}
bitflags = "1.3.2"
bytemuck = "1.8.0"
clap = {version = "3.1.6", features = ["derive"]}
futures = "0.3"
heron = {path = "./crates/heron", features = ["3d"]}
image = "0.24.1"
names = {version = "0.13.0", default-features = false}
rand = "0.8.4"
rocket = "0.5.0-rc.1"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = {version = "1.17.0", features = ["full"]}
wgpu = "0.12.0"

[profile.dev]
opt-level = 3
