[package]
edition = "2021"
name = "bevystein"
version = "0.0.1"

[dependencies]
bevy = {package = "bevy", git = "https://github.com/bevyengine/bevy.git", rev = "9e450f2"}
bevy_mod_raycast = {path = "./crates/bevy_mod_raycast"}
bevy_rl = {path = "./crates/bevy_rl"}
big-brain = {path = "./crates/big-brain"}
bitflags = "1.3.2"
clap = "3.1.6"
heron = {path = "./crates/heron", features = ["3d"]}
image = "0.24.1"
names = {version = "0.13.0", default-features = false}
rand = "0.8.4"
serde = "1.0.136"
serde_json = "1.0.79"
crossbeam-channel = "0.5"

[profile.dev]
opt-level = 3
